services:
  - type: web
    name: json-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: json-server --watch db.json --port 3000
    envVars:
      - key: NODE_ENV
        value: production
